import React from 'react';
import { Amplify } from 'aws-amplify';
import awsExports from './aws-exports'; // Generated by Amplify
import Login from './Login';
import Signup from './Signup';

Amplify.configure(awsExports);

function App() {
  return (
    <div>
      <h1>Welcome to Neighbormate</h1>
      <Login />
    </div>
  );
}

export default App;

